#!/bin/env bash

echo -e "\e[1;32m Step 1: Updating | Upgrading packages\n=====================================\e[0m"
sudo apt update -y && sudo apt upgrade -y

echo

echo -e "\e[1;32m Step 2: Uninstalling the package\n=====================================\e[0m"
sudo apt remove --purge -y $1

echo

echo -e "\e[1;32m Step 3: Repairing broken packages/dependencies\n=============================================\e[0m"
sudo apt --fix-missing update -y
sudo apt update -y
sudo apt install -f -y

echo

echo -e "\e[1;32m Step 4: Removing orphaned packages and dependencies\n====================================================\e[0m"
sudo apt autoremove --purge -y

echo

echo -e "\e[1;32m Step 5: Removing all the junk files\n=====================================\e[0m"
sudo apt clean -y
sudo apt autoclean -y

echo

echo -e "\e[1;32m Last step: Updating packages\n==============================\e[0m"
sudo apt update -y && sudo apt upgrade -y

echo

echo -e "\e[1;32m \tCONGRATULATIONS $USER!!\n \tYour system is clean and up-to-date\e[0m"

echo
